Repository animal-crossing-music-extension/ac-music-extension, pull requests merged in 2020-02, with the labels that each got.

#81 Add: option to pause music when browser is closed
  options.html
  scripts/background/StateManager.js
  scripts/options/options.js
Labels: new feature

#76 Update: backend domain + about page overhaul
  css/options.css
  manifest.json
  options.html
  scripts/background/AudioManager.js
  scripts/background/MediaSessionManager.js
  scripts/background/WeatherManager.js
  scripts/options/contributors.js
  scripts/options/options.js
Labels: enhancement

#77 Fix: timekeeper's hourly check function
  options.html
  scripts/background/TimeKeeper.js
Labels: bug

#82 Update: remove need for tabs permission
  css/options.css
  manifest.json
  options.html
  scripts/background/StateManager.js
  scripts/background/TabAudioHandler.js
  scripts/options/options.js
Labels: enhancement

#83 Enhancements & additions to the town tune editor & player
  css/input.css
  options.html
  scripts/background/StateManager.js
  scripts/background/TownTuneManager.js
  scripts/global/tune_player.js
  scripts/options/options.js
  scripts/options/tune_editor.js
Labels: enhancement
